/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CheersBoard {
  export type PostStruct = {
    postId: BigNumberish;
    wallId: BigNumberish;
    author: AddressLike;
    title: string;
    content: string;
    mediaCID: string;
    timestamp: BigNumberish;
    removed: boolean;
    encryptedLikeCount: BytesLike;
  };

  export type PostStructOutput = [
    postId: bigint,
    wallId: bigint,
    author: string,
    title: string,
    content: string,
    mediaCID: string,
    timestamp: bigint,
    removed: boolean,
    encryptedLikeCount: string
  ] & {
    postId: bigint;
    wallId: bigint;
    author: string;
    title: string;
    content: string;
    mediaCID: string;
    timestamp: bigint;
    removed: boolean;
    encryptedLikeCount: string;
  };

  export type WallStruct = {
    wallId: BigNumberish;
    organizer: AddressLike;
    title: string;
    description: string;
    coverCID: string;
    startTime: BigNumberish;
    endTime: BigNumberish;
    allowAnonymous: boolean;
    allowMedia: boolean;
    postFee: BigNumberish;
    autoMint: boolean;
  };

  export type WallStructOutput = [
    wallId: bigint,
    organizer: string,
    title: string,
    description: string,
    coverCID: string,
    startTime: bigint,
    endTime: bigint,
    allowAnonymous: boolean,
    allowMedia: boolean,
    postFee: bigint,
    autoMint: boolean
  ] & {
    wallId: bigint;
    organizer: string;
    title: string;
    description: string;
    coverCID: string;
    startTime: bigint;
    endTime: bigint;
    allowAnonymous: boolean;
    allowMedia: boolean;
    postFee: bigint;
    autoMint: boolean;
  };
}

export interface CheersBoardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createWall"
      | "getEncryptedLikeCount"
      | "getPost"
      | "getPostsByWall"
      | "getWall"
      | "likePost"
      | "nextPostId"
      | "nextWallId"
      | "postBlessing"
      | "posts"
      | "protocolId"
      | "removePost"
      | "wallToPosts"
      | "walls"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PostCreated"
      | "PostLiked"
      | "PostRemoved"
      | "WallCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createWall",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedLikeCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPostsByWall",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWall",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "likePost",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPostId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextWallId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "postBlessing",
    values: [BigNumberish, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removePost",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "wallToPosts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "walls", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "createWall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedLikeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPostsByWall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likePost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextPostId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextWallId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postBlessing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removePost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wallToPosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "walls", data: BytesLike): Result;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    wallId: BigNumberish,
    postId: BigNumberish,
    author: AddressLike,
    title: string
  ];
  export type OutputTuple = [
    wallId: bigint,
    postId: bigint,
    author: string,
    title: string
  ];
  export interface OutputObject {
    wallId: bigint;
    postId: bigint;
    author: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostLikedEvent {
  export type InputTuple = [
    wallId: BigNumberish,
    postId: BigNumberish,
    from: AddressLike
  ];
  export type OutputTuple = [wallId: bigint, postId: bigint, from: string];
  export interface OutputObject {
    wallId: bigint;
    postId: bigint;
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostRemovedEvent {
  export type InputTuple = [
    wallId: BigNumberish,
    postId: BigNumberish,
    moderator: AddressLike
  ];
  export type OutputTuple = [wallId: bigint, postId: bigint, moderator: string];
  export interface OutputObject {
    wallId: bigint;
    postId: bigint;
    moderator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WallCreatedEvent {
  export type InputTuple = [
    wallId: BigNumberish,
    organizer: AddressLike,
    title: string,
    coverCID: string
  ];
  export type OutputTuple = [
    wallId: bigint,
    organizer: string,
    title: string,
    coverCID: string
  ];
  export interface OutputObject {
    wallId: bigint;
    organizer: string;
    title: string;
    coverCID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CheersBoard extends BaseContract {
  connect(runner?: ContractRunner | null): CheersBoard;
  waitForDeployment(): Promise<this>;

  interface: CheersBoardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createWall: TypedContractMethod<
    [
      title: string,
      description: string,
      coverCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      allowAnonymous: boolean,
      allowMedia: boolean,
      postFee: BigNumberish,
      autoMint: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getEncryptedLikeCount: TypedContractMethod<
    [wallId: BigNumberish, postId: BigNumberish],
    [string],
    "view"
  >;

  getPost: TypedContractMethod<
    [postId: BigNumberish],
    [CheersBoard.PostStructOutput],
    "view"
  >;

  getPostsByWall: TypedContractMethod<
    [wallId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getWall: TypedContractMethod<
    [wallId: BigNumberish],
    [CheersBoard.WallStructOutput],
    "view"
  >;

  likePost: TypedContractMethod<
    [
      wallId: BigNumberish,
      postId: BigNumberish,
      encryptedIncrement: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  nextPostId: TypedContractMethod<[], [bigint], "view">;

  nextWallId: TypedContractMethod<[], [bigint], "view">;

  postBlessing: TypedContractMethod<
    [wallId: BigNumberish, title: string, content: string, mediaCID: string],
    [bigint],
    "payable"
  >;

  posts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        string
      ] & {
        postId: bigint;
        wallId: bigint;
        author: string;
        title: string;
        content: string;
        mediaCID: string;
        timestamp: bigint;
        removed: boolean;
        encryptedLikeCount: string;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removePost: TypedContractMethod<
    [wallId: BigNumberish, postId: BigNumberish],
    [void],
    "nonpayable"
  >;

  wallToPosts: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  walls: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        wallId: bigint;
        organizer: string;
        title: string;
        description: string;
        coverCID: string;
        startTime: bigint;
        endTime: bigint;
        allowAnonymous: boolean;
        allowMedia: boolean;
        postFee: bigint;
        autoMint: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createWall"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      coverCID: string,
      startTime: BigNumberish,
      endTime: BigNumberish,
      allowAnonymous: boolean,
      allowMedia: boolean,
      postFee: BigNumberish,
      autoMint: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedLikeCount"
  ): TypedContractMethod<
    [wallId: BigNumberish, postId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPost"
  ): TypedContractMethod<
    [postId: BigNumberish],
    [CheersBoard.PostStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPostsByWall"
  ): TypedContractMethod<[wallId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getWall"
  ): TypedContractMethod<
    [wallId: BigNumberish],
    [CheersBoard.WallStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "likePost"
  ): TypedContractMethod<
    [
      wallId: BigNumberish,
      postId: BigNumberish,
      encryptedIncrement: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPostId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextWallId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "postBlessing"
  ): TypedContractMethod<
    [wallId: BigNumberish, title: string, content: string, mediaCID: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        string
      ] & {
        postId: bigint;
        wallId: bigint;
        author: string;
        title: string;
        content: string;
        mediaCID: string;
        timestamp: bigint;
        removed: boolean;
        encryptedLikeCount: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removePost"
  ): TypedContractMethod<
    [wallId: BigNumberish, postId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wallToPosts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "walls"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        wallId: bigint;
        organizer: string;
        title: string;
        description: string;
        coverCID: string;
        startTime: bigint;
        endTime: bigint;
        allowAnonymous: boolean;
        allowMedia: boolean;
        postFee: bigint;
        autoMint: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PostLiked"
  ): TypedContractEvent<
    PostLikedEvent.InputTuple,
    PostLikedEvent.OutputTuple,
    PostLikedEvent.OutputObject
  >;
  getEvent(
    key: "PostRemoved"
  ): TypedContractEvent<
    PostRemovedEvent.InputTuple,
    PostRemovedEvent.OutputTuple,
    PostRemovedEvent.OutputObject
  >;
  getEvent(
    key: "WallCreated"
  ): TypedContractEvent<
    WallCreatedEvent.InputTuple,
    WallCreatedEvent.OutputTuple,
    WallCreatedEvent.OutputObject
  >;

  filters: {
    "PostCreated(uint256,uint256,address,string)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "PostLiked(uint256,uint256,address)": TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;
    PostLiked: TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;

    "PostRemoved(uint256,uint256,address)": TypedContractEvent<
      PostRemovedEvent.InputTuple,
      PostRemovedEvent.OutputTuple,
      PostRemovedEvent.OutputObject
    >;
    PostRemoved: TypedContractEvent<
      PostRemovedEvent.InputTuple,
      PostRemovedEvent.OutputTuple,
      PostRemovedEvent.OutputObject
    >;

    "WallCreated(uint256,address,string,string)": TypedContractEvent<
      WallCreatedEvent.InputTuple,
      WallCreatedEvent.OutputTuple,
      WallCreatedEvent.OutputObject
    >;
    WallCreated: TypedContractEvent<
      WallCreatedEvent.InputTuple,
      WallCreatedEvent.OutputTuple,
      WallCreatedEvent.OutputObject
    >;
  };
}
